### ISSUE TITLE
Warns don't save

### ISSUE THREAD

**Issue by Aericio** [robske110/BanWarn#11]
Using latest version of BanWarn
After a player relogs from the server, the warn is gone.

**Comment by robske110** [comment]
what? please explain that a little bit more

**Comment by Aericio** [comment]
Edited comment

**Comment by robske110** [comment]
can't reproduce with BanWarn 1.2.0 beta2

**Comment by Aericio** [comment]
I think it was a reload, not relog

**Comment by robske110** [comment]
you're using the english version right?
I can't reproduce this at all.
May you send the BanWarn plugin folder (after and before the whatever-you-do-to-magically-remove-a-warn, and some parts of the log?)

**Comment by robske110** [comment]
?

**Comment by Aericio** [comment]
Oh sorry I'll send one.

**Comment by Aericio** [comment]
Console broke ;-; Might have to wait a few weeks...

**Comment by robske110** [comment]
:(

**Comment by Aericio** [comment]
Seems like it doesn't happen anymore, maybe file save just got messed up.
