### ISSUE TITLE
API 3.0.0-ALPHA6

### ISSUE THREAD

**Issue by TheShinPin** [robske110/BanWarn#19]
Was wondering if you could make a version for API 3.0.0-ALPHA6, since most plugins aren't using ALPHA7, so their are a lot of compatibility issues. If you could that would be great. Thanks!

**Comment by robske110** [comment]
Well, here you have 1.2.1 patched for 3.0.0-ALPHA3-6
[BanWarn-1.2.1-3.0.0-ALPHA3-6.phar.zip](https://github.com/robske110/BanWarn/files/1165584/BanWarn-1.2.1-3.0.0-ALPHA3-6.phar.zip)
