### ISSUE TITLE
Notify Mode?

### ISSUE THREAD

**Issue by TheShinPin** [robske110/BanWarn#20]
I was wondering what the notify mode in the config did. Thanks

**Comment by robske110** [comment]
Notify-Mode 1 notifies only the console+the player who was warned+the player who warned the player about the warn and Notify-Mode 2 notifies every player and the console. This should be better documented, you're right. But this is currently a project on hold.
https://github.com/robske110/BanWarn/blob/master/English/src/robske_110/BanWarn/Main.php#L221-L228
