### ISSUE TITLE
I need this for a project

### ISSUE THREAD

**Issue by ghost** [robske110/BanWarn#22]
Hey robske110. I’m IJustEditBuilds and I see that your plugin works very well. Im asking you permission for use this plugin for a big project called CrimeTools and I need this plugin. Would you let me use this plugin. Thank you

**Comment by Aericio** [comment]
You're allowed to use this plugin for private purposes, but I am assuming that you want to add it to your "big project"? I don't recommend that and, if any errors occur as a result of that, we will not provide any support. Use BanWarn's API instead of including it in the actual plugin.

**Comment by robske110** [comment]
You are free to use this plugin and code according to the GPL license the code is licensed under: https://github.com/robske110/BanWarn/blob/master/LICENSE (you have to release any modifications made publicly, for example).
But please keep the points Aericio said in mind.

**Comment by ghost** [comment]
Ok thanks
