### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by LordTheMini** [robske110/BanWarn#8]
![screenshot_2016-05-23-14-29-44](https://cloud.githubusercontent.com/assets/15161069/15470824/0ba44c44-20f3-11e6-9027-76fa2018065e.png)

**Comment by robske110** [comment]
Wich version are you using?
If you are not using BanWarn_v1.2.0-InDev-beta2_pre1_deu.phar please download it from here:
https://github.com/robske110/BanWarn/tree/master/Releases/1.2.X/ALPHAS:BETAS

Welche version benutzt du?
Falls du nicht BanWarn_v1.2.0-InDev-beta2_pre1_deu.phar benutzt lade dir diese bitte von hier herunter:
https://github.com/robske110/BanWarn/tree/master/Releases/1.2.X/ALPHAS:BETAS

**Comment by robske110** [comment]
?

**Comment by robske110** [comment]
Closing due to not enough info and no response

**Comment by LordTheMini** [comment]
Also ich nutze die Neuste Version von banwarn. Ich gebe /warnpardon [Mein IGN] ein danach soll ich all oder last eingeben. Egal ob all oder last, es funktioniert nicht

**Comment by robske110** [comment]
Versuchs mal hiermit:
https://github.com/robske110/BanWarn/blob/master/Releases/1.2.X/ALPHAS:BETAS/BanWarn_v1.2.0-InDev-beta2_pre1_deu.phar

**Comment by robske110** [comment]
Sorry for any inconvenience caused, this has now been fixed, and please try beta2 (not pre1)
